import ArticleList from "./article-list.js";
import ArticlePage from "./article-page.js";
import ArticlePreview from "./article-preview.js";
import CommentList from "./comment-list.js";
import ConduitApp from "./conduit-app.js";
import EditorPage from "./editor-page.js";
import ErrorList from "./error-list.js";
import FavoriteButton from "./favorite-button.js";
import FollowButton from "./follow-button.js";
import HomePage from "./home-page.js";
import IntlFormat from "./intl-format.js";
import LoginPage from "./login-page.js";
import NavLink from "./nav-link.js";
import PageRouter from "./page-router.js";
import PaginationNav from "./pagination-nav.js";
import PopularTags from "./popular-tags.js";
import ProfilePage from "./profile-page.js";
import RegisterPage from "./register-page.js";
import SettingsPage from "./settings-page.js";
import TagsInput from "./tags-input.js";

customElements.define("article-list", ArticleList);
customElements.define("article-page", ArticlePage);
customElements.define("article-preview", ArticlePreview);
customElements.define("comment-list", CommentList);
customElements.define("conduit-app", ConduitApp);
customElements.define("editor-page", EditorPage);
customElements.define("error-list", ErrorList);
customElements.define("favorite-button", FavoriteButton);
customElements.define("follow-button", FollowButton);
customElements.define("home-page", HomePage);
customElements.define("intl-format", IntlFormat);
customElements.define("login-page", LoginPage);
customElements.define("nav-link", NavLink);
customElements.define("page-router", PageRouter);
customElements.define("pagination-nav", PaginationNav);
customElements.define("popular-tags", PopularTags);
customElements.define("profile-page", ProfilePage);
customElements.define("register-page", RegisterPage);
customElements.define("settings-page", SettingsPage);
customElements.define("tags-input", TagsInput);
